In [53]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [54]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [55]:
# Preprocess the data
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [56]:
# Encode categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [57]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [58]:
onehot_encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

onehot_encoded = onehot_encoder.fit_transform(data[['Geography', 'Gender']])

onehot_encoded_df = pd.DataFrame(
    onehot_encoded,
    columns=onehot_encoder.get_feature_names_out(['Geography', 'Gender'])
)

onehot_encoded_df

      Geography_France  Geography_Germany  Geography_Spain  Gender_0  Gender_1
0                  1.0                0.0              0.0       1.0       0.0
1                  0.0                0.0              1.0       1.0       0.0
2                  1.0                0.0              0.0       1.0       0.0
3                  1.0                0.0              0.0       1.0       0.0
4                  0.0                0.0              1.0       1.0       0.0
...                ...                ...              ...       ...       ...
9995               1.0                0.0              0.0       0.0       1.0
9996               1.0                0.0              0.0       0.0       1.0
9997               1.0                0.0              0.0       1.0       0.0
9998               0.0                1.0              0.0       0.0       1.0
9999               1.0                0.0              0.0       1.0       0.0

[10000 rows x 5 columns]

In [59]:
data = pd.concat([data.drop(['Geography', 'Gender'], axis=1), onehot_encoded_df], axis=1)

data.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain,Gender_0,Gender_1
0,619,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0,1.0,0.0
1,608,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0,1.0,0.0
2,502,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0,1.0,0.0
3,699,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0,1.0,0.0
4,850,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0,1.0,0.0

In [60]:
# Split the data into features and target
x = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [61]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [62]:
scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [63]:
import pickle

with open("label_encoder_gender.pkl", "wb") as file:
    pickle.dump(label_encoder_gender, file)

with open("onehot_encoder.pkl", "wb") as file:
    pickle.dump(onehot_encoder, file)

with open("scaler.pkl", "wb") as file:
    pickle.dump(scaler, file)

#### ANN Regression Problem statement

In [64]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [65]:
model = Sequential([
    Dense(64, activation='relu', input_shape=(x_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

c:\Users\Gaurish16\OneDrive\Desktop\Udemy\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,009 (11.75 KB)

 Trainable params: 3,009 (11.75 KB)

 Non-trainable params: 0 (0.00 B)

In [66]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

log_dir = "classificationlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

tensorboard_callback = TensorBoard(
    log_dir=log_dir,
    histogram_freq=1
)

In [67]:
early_stopping_callback = EarlyStopping(
    monitor='val_loss',
    patience=10,
    restore_best_weights=True
)

In [69]:
print(x_train.shape)
print(y_train.shape)

(8000, 13)
(8000,)

In [71]:
history = model.fit(
    x_train,
    y_train,
    validation_data=(x_test, y_test),
    epochs=100,
    batch_size=32,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0000e+00 - loss: -4917247.5000 - val_accuracy: 0.0000e+00 - val_loss: -18838456.0000
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -74022440.0000 - val_accuracy: 0.0000e+00 - val_loss: -157654448.0000
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -328426112.0000 - val_accuracy: 0.0000e+00 - val_loss: -534796384.0000
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -872096000.0000 - val_accuracy: 0.0000e+00 - val_loss: -1237539584.0000
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -1784071296.0000 - val_accuracy: 0.0000e+00 - val_loss: -2330010112.0000
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -3123042560.0000 - val_accuracy: 0.0000e+00 - val_loss: -3867375616.0000
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -4938783744.0000 - val_accuracy: 0.0000e+00 - val_loss: -5892270080.0000
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -7265915392.0000 - val_accuracy: 0.0000e+00 - val_loss: -8428161024.0000
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: -10134882304.0000 - val_accuracy: 0.0000e+00 - val_loss: -11509752832.0000
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: -13570613248.0000 - val_accuracy: 0.0000e+00 - val_loss: -15159588864.0000
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -17600110592.0000 - val_accuracy: 0.0000e+00 - val_loss: -19394482176.0000
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -22240116736.0000 - val_accuracy: 0.0000e+00 - val_loss: -24246099968.0000
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -27508295680.0000 - val_accuracy: 0.0000e+00 - val_loss: -29717092352.0000
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -33436559360.0000 - val_accuracy: 0.0000e+00 - val_loss: -35836604416.0000
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -40031981568.0000 - val_accuracy: 0.0000e+00 - val_loss: -42621034496.0000
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -47302504448.0000 - val_accuracy: 0.0000e+00 - val_loss: -50059792384.0000
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -55275057152.0000 - val_accuracy: 0.0000e+00 - val_loss: -58222051328.0000
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -63965216768.0000 - val_accuracy: 0.0000e+00 - val_loss: -67068465152.0000
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -73384452096.0000 - val_accuracy: 0.0000e+00 - val_loss: -76662996992.0000
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -83552256000.0000 - val_accuracy: 0.0000e+00 - val_loss: -86950805504.0000
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -94482735104.0000 - val_accuracy: 0.0000e+00 - val_loss: -98024226816.0000
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -106187063296.0000 - val_accuracy: 0.0000e+00 - val_loss: -109855817728.0000
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -118690406400.0000 - val_accuracy: 0.0000e+00 - val_loss: -122483261440.0000
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -132017446912.0000 - val_accuracy: 0.0000e+00 - val_loss: -135918321664.0000
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -146162466816.0000 - val_accuracy: 0.0000e+00 - val_loss: -150166945792.0000
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: -161157611520.0000 - val_accuracy: 0.0000e+00 - val_loss: -165233639424.0000
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: -177023025152.0000 - val_accuracy: 0.0000e+00 - val_loss: -181184839680.0000
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -193786494976.0000 - val_accuracy: 0.0000e+00 - val_loss: -198016008192.0000
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -211443744768.0000 - val_accuracy: 0.0000e+00 - val_loss: -215717396480.0000
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -230027231232.0000 - val_accuracy: 0.0000e+00 - val_loss: -234393878528.0000
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -249558925312.0000 - val_accuracy: 0.0000e+00 - val_loss: -253942710272.0000
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -270054326272.0000 - val_accuracy: 0.0000e+00 - val_loss: -274447384576.0000
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -291528212480.0000 - val_accuracy: 0.0000e+00 - val_loss: -295914569728.0000
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -314018136064.0000 - val_accuracy: 0.0000e+00 - val_loss: -318401282048.0000
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -337529864192.0000 - val_accuracy: 0.0000e+00 - val_loss: -341906063360.0000
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -362079256576.0000 - val_accuracy: 0.0000e+00 - val_loss: -366421573632.0000
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: -387676635136.0000 - val_accuracy: 0.0000e+00 - val_loss: -391960068096.0000
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -414337302528.0000 - val_accuracy: 0.0000e+00 - val_loss: -418616115200.0000
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -442094485504.0000 - val_accuracy: 0.0000e+00 - val_loss: -446239309824.0000
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -470963847168.0000 - val_accuracy: 0.0000e+00 - val_loss: -475047591936.0000
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -500967571456.0000 - val_accuracy: 0.0000e+00 - val_loss: -504897961984.0000
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -532111523840.0000 - val_accuracy: 0.0000e+00 - val_loss: -535985324032.0000
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: -564404879360.0000 - val_accuracy: 0.0000e+00 - val_loss: -568183095296.0000
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: -597892399104.0000 - val_accuracy: 0.0000e+00 - val_loss: -601446350848.0000
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: -632600526848.0000 - val_accuracy: 0.0000e+00 - val_loss: -635962261504.0000
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -668539486208.0000 - val_accuracy: 0.0000e+00 - val_loss: -671732137984.0000
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -705685946368.0000 - val_accuracy: 0.0000e+00 - val_loss: -708658200576.0000
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: -744093057024.0000 - val_accuracy: 0.0000e+00 - val_loss: -746772168704.0000
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: -783741747200.0000 - val_accuracy: 0.0000e+00 - val_loss: -786223005696.0000
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: -824688377856.0000 - val_accuracy: 0.0000e+00 - val_loss: -826915225600.0000
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: -866973384704.0000 - val_accuracy: 0.0000e+00 - val_loss: -868943855616.0000
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -910589231104.0000 - val_accuracy: 0.0000e+00 - val_loss: -912123363328.0000
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -955561017344.0000 - val_accuracy: 0.0000e+00 - val_loss: -956846178304.0000
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -1001931735040.0000 - val_accuracy: 0.0000e+00 - val_loss: -1002862542848.0000
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -1049633423360.0000 - val_accuracy: 0.0000e+00 - val_loss: -1050178486272.0000
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: -1098709532672.0000 - val_accuracy: 0.0000e+00 - val_loss: -1098884055040.0000
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: -1149186605056.0000 - val_accuracy: 0.0000e+00 - val_loss: -1148871376896.0000
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: -1201115627520.0000 - val_accuracy: 0.0000e+00 - val_loss: -1200359473152.0000
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -1254481461248.0000 - val_accuracy: 0.0000e+00 - val_loss: -1253319376896.0000
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -1309284368384.0000 - val_accuracy: 0.0000e+00 - val_loss: -1307668774912.0000
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -1365581103104.0000 - val_accuracy: 0.0000e+00 - val_loss: -1363341475840.0000
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -1423398797312.0000 - val_accuracy: 0.0000e+00 - val_loss: -1420696748032.0000
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -1482758815744.0000 - val_accuracy: 0.0000e+00 - val_loss: -1479430111232.0000
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -1543709786112.0000 - val_accuracy: 0.0000e+00 - val_loss: -1539737911296.0000
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -1606173720576.0000 - val_accuracy: 0.0000e+00 - val_loss: -1601663401984.0000
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -1670211436544.0000 - val_accuracy: 0.0000e+00 - val_loss: -1665004863488.0000
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -1735828832256.0000 - val_accuracy: 0.0000e+00 - val_loss: -1730101641216.0000
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -1803097604096.0000 - val_accuracy: 0.0000e+00 - val_loss: -1796493017088.0000
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: -1871996649472.0000 - val_accuracy: 0.0000e+00 - val_loss: -1864672083968.0000
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -1942492807168.0000 - val_accuracy: 0.0000e+00 - val_loss: -1934439350272.0000
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: -2014616223744.0000 - val_accuracy: 0.0000e+00 - val_loss: -2005866905600.0000
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: -2088502165504.0000 - val_accuracy: 0.0000e+00 - val_loss: -2078910709760.0000
Epoch 73/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -2164087455744.0000 - val_accuracy: 0.0000e+00 - val_loss: -2153627254784.0000
Epoch 74/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -2241342996480.0000 - val_accuracy: 0.0000e+00 - val_loss: -2229983248384.0000
Epoch 75/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -2320335634432.0000 - val_accuracy: 0.0000e+00 - val_loss: -2307980525568.0000
Epoch 76/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -2401094336512.0000 - val_accuracy: 0.0000e+00 - val_loss: -2388045856768.0000
Epoch 77/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -2483605995520.0000 - val_accuracy: 0.0000e+00 - val_loss: -2469394907136.0000
Epoch 78/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -2567925399552.0000 - val_accuracy: 0.0000e+00 - val_loss: -2552593645568.0000
Epoch 79/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -2654027644928.0000 - val_accuracy: 0.0000e+00 - val_loss: -2637886128128.0000
Epoch 80/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: -2741924265984.0000 - val_accuracy: 0.0000e+00 - val_loss: -2724575576064.0000
Epoch 81/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -2831579873280.0000 - val_accuracy: 0.0000e+00 - val_loss: -2813136994304.0000
Epoch 82/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -2923091197952.0000 - val_accuracy: 0.0000e+00 - val_loss: -2903563567104.0000
Epoch 83/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -3016543436800.0000 - val_accuracy: 0.0000e+00 - val_loss: -2995746766848.0000
Epoch 84/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -3111778516992.0000 - val_accuracy: 0.0000e+00 - val_loss: -3089962369024.0000
Epoch 85/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -3208991211520.0000 - val_accuracy: 0.0000e+00 - val_loss: -3185835507712.0000
Epoch 86/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -3308143771648.0000 - val_accuracy: 0.0000e+00 - val_loss: -3283773816832.0000
Epoch 87/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -3409263198208.0000 - val_accuracy: 0.0000e+00 - val_loss: -3383465607168.0000
Epoch 88/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -3512324587520.0000 - val_accuracy: 0.0000e+00 - val_loss: -3485319561216.0000
Epoch 89/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -3617374339072.0000 - val_accuracy: 0.0000e+00 - val_loss: -3589048107008.0000
Epoch 90/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -3724448890880.0000 - val_accuracy: 0.0000e+00 - val_loss: -3694866726912.0000
Epoch 91/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -3833542213632.0000 - val_accuracy: 0.0000e+00 - val_loss: -3802277347328.0000
Epoch 92/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -3944701231104.0000 - val_accuracy: 0.0000e+00 - val_loss: -3911900200960.0000
Epoch 93/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -4057900253184.0000 - val_accuracy: 0.0000e+00 - val_loss: -4023523475456.0000
Epoch 94/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -4173139804160.0000 - val_accuracy: 0.0000e+00 - val_loss: -4137292136448.0000
Epoch 95/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -4290372435968.0000 - val_accuracy: 0.0000e+00 - val_loss: -4253093199872.0000
Epoch 96/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -4409650053120.0000 - val_accuracy: 0.0000e+00 - val_loss: -4370764398592.0000
Epoch 97/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -4531161137152.0000 - val_accuracy: 0.0000e+00 - val_loss: -4490510467072.0000
Epoch 98/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -4654861647872.0000 - val_accuracy: 0.0000e+00 - val_loss: -4612632346624.0000
Epoch 99/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -4780716457984.0000 - val_accuracy: 0.0000e+00 - val_loss: -4736595525632.0000
Epoch 100/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: -4908646400000.0000 - val_accuracy: 0.0000e+00 - val_loss: -4862723489792.0000

In [72]:
%load_ext tensorboard

In [73]:
%tensorboard --logdir regressionlogs/fit

In [74]:
## Evaluate model on the test data
test_loss,test_mae=model.evaluate(x_test,y_test)
print(f'Test MAE : {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -4862723489792.0000
Test MAE : 0.0

In [75]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.